---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocp-api-certificate
  namespace: openshift-config
spec:
  isCA: false
  commonName: "api.$CLUSTER_DOMAIN"
  dnsNames:
    - "api.$CLUSTER_DOMAIN"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: api-cert-secret
  