---
apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  name: cluster
  annotations:
    #argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    #argocd.argoproj.io/sync-wave: "05"
spec:
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  unsupportedConfigOverrides: null
  controllerConfig:                                
    overrideArgs:
      - '--dns01-recursive-nameservers-only'       
      - '--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53'
      # Deleting a TLS secret automatically upon Certificate removal
      - '--enable-certificate-owner-ref'