---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocp-ingress-certificate
  namespace: openshift-ingress
  annotations:
    #argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    #argocd.argoproj.io/sync-wave: "10"
spec:
  isCA: false
  commonName: "apps.$CLUSTER_DOMAIN"
  dnsNames:
  - "apps.$CLUSTER_DOMAIN"
  - "*.apps.$CLUSTER_DOMAIN"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: ingress-cert-secret