---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        route53:
          region: eu-west-1
          #region: eu-central-1
          accessKeyIDSecretRef:
            name: route53-credentials-secrets
            key: access-key-id
          secretAccessKeySecretRef:
            name: route53-credentials-secrets
            key: secret-access-key
      selector:
        dnsZones:
          - $CLUSTER_DOMAIN
