apiVersion: v1
kind: Namespace
metadata:
  name: cert-utils-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cert-utils-operator
  namespace: cert-utils-operator
spec:
  upgradeStrategy: Default
  #targetNamespaces:
    #- ""
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/cert-utils-operator.cert-utils-operator: ''
  name: cert-utils-operator
  namespace: cert-utils-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  #this below is package name: cert-utils-operator
  name: cert-utils-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  #startingCSV: cert-utils-operator.v1.3.12