apiVersion: v1
kind: Namespace
metadata:
  name: cert-utils-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cert-utils-operator.cert-utils-operator
  namespace: cert-utils-operator
spec:  
  upgradeStrategy: Default
  targetNamespaces:
    - cert-utils-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/cert-utils-operator.cert-utils-operator: ''
  name: cert-utils-operator
  namespace: cert-utils-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: cert-utils-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
